name: 同步到 LuckyServer
on:
  push:
    branches:
      - master

jobs:
  hexo-deployment:
    runs-on: ubuntu-latest
    env:
      TZ: Asia/Shanghai

    steps:
    - name: Checkout source
      uses: actions/checkout@v2
      with:
      submodules: true

    - name: 安装 Node.js
      uses: actions/setup-node@v1
      with:
      node-version: '16.8.0'

    - name: 安装依赖 & 生成静态文件
      run: |
        node -v
        npm i -g hexo-cli
        npm i
        hexo clean
        hexo g

      - name: 上传到 LuckyServer
        uses: SamKirkland/FTP-Deploy-Action@2.0.0
        env:
          FTP_SERVER: ipv4.luckykeeper.site
          FTP_USERNAME: love69_luckykeeper_site
          FTP_PASSWORD: ${{ secrets.MIRROR_FTP_PS }}
          # port: 21
          LOCAL_DIR: public
          REMOTE_DIR: /
          ARGS: --delete --transfer-all --exclude=logreport --verbose